replicaCount: 1
image:
  repository: ghcr.io/akaclasses/todo-api-python
  tag: 4741c347d51dc607a7a44d581f9a34e40d0c8963
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
env:
  NODE_ENV: production
  PORT: "8000"
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"