---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: todo-api-secret
  namespace: todo-api-dev
spec:
  encryptedData:
    DATABASE_URL: AgCQGdYPgXJZqWJoBDUEDha1NEjc/BIl/zmHGcypEsOVqaLXFGfw7obm2u45EaPV5E2Dz6Igr2qnuVcYRzPENAgaO6Hz5bBjrPEcO5B0QgytQili8iABhdkeu8WPAIVi621x4DRs7+NGNd7mA34TvqR6GYljolDi7qR4H5KqdFqQLVKvLKK+UK/5DS3GiGxDuqZOIjkCHFIw3GjBkXCwuu7noGar3mswzNdfpwnxkuhAtYDs8H96zS6pbSCai/7LrA+QOYPC7ekSYmiQTeras9JfR5rZHQl9W2078366wDRLoS2e/+5EuT4yiYw+XSe0qaJ3s3iPBkZbIWMyQC36UH1HIsTd+ST4MMui+L+GcSsUJG16Y29tcXslL4TNMh4tpFUgYVfaet18H3hzCd+3Af+xry+JvOyYvku/XTWXhvymDNIxAb6xXH583v99nkfzcOJygm78QA2MjTp+OHEqw7gZCb4UF+pG5v7ZbXKe7v1DHb1imt0ShRomfDq9riU2NbTdxcevbgyzW6rewYic1VA/Vgx+OMLIrFqQH6U2DRmJ9ISIgPN0UsOC3e1U8xd8txszAJ9laALgHXFYyjhz7VvdfrT9n1O9Tlab7pdA8/Alw0kcJNP3zQqugTNZxw8TRvlxU9dN8FGEQr5ZwcPnHjK4++ScGXw1Hv+Y0loGfaJFL8Tw4U48aoWFQSs3nfbCr5/jWtUFKsYPVreBBfnYqLbm+urN
    SECRET_KEY: AgA8jAhutMXxMpgyuzlCx7ea5sfUsKrQCvvRp9sOigh6KZzU85nSaRnm9/vEMfSAOURZQj49B3AOzFfLTstV5mU0t/J0ElHpD6K39a7vCovua9QD1DjxnFJz1ftZ4WQ/uJULsx7b7Fvf9h8Q96beW4iVPUxZHjZ3VT1sM24k8r9m/xP0EXOiHvuRqlXeb6JV7PUrJWuhmfi4YgpwxKdTFMnfm+/0xa/b+FBlczLiYfcDZ9jgbW9ht2bHBnJy6BQc1hvROrBW1FH+lRWihxgHJM4EXGHST4z+P5FPuCPQ/OVwGf4i6JYvn7IbmuIwK4JnOJ7DzFWD79KSlhxmvJ29XAIFhOh0xs9M9kXjGWiPpNNt/ypq0eDlinFyLPf/1ofT1FSJmXghBW3E5MsfgM7F1djnl8PWRCKEJHF8pAVHjU+Kn7eCvCGQmloARRUMusEgVdyzGfQCMAV+lZwmapMpZJsjaNpB4oEmLbqVklt0veRUzvsmPjc0dxn8yPXLPimmZyV4+Ef+Uh5aee6DXftEYoV2tAcNN9Q++VSISFWg/opcoJu2/6RyUPaJbdCX7dpukntjNWz3p6FRuiOwraGtbVERNqpaJm7/xrAtyQENJTi+NUdqvBEWFpxReg1EULM8QdmDMLutVubtRNeBJWixqY5EetWWeavrTuM5/eoRsccFkTxC9NdexF9JCL51Sdwx1Asu6tPpzVNMn8JL2PH5z6m5ihOF/80NOTo+xFvoGX2YiJnCsQHg0qwJOTDggyA/fPDEyPyqAufeApbFikr2GWJ7
  template:
    metadata:
      name: todo-api-secret
      namespace: todo-api-dev
