apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-team-ryuk
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/adouadi28-arch/gitops-team-Ryuk
  ref:
    branch: main
